<a href="https://colab.research.google.com/github/Analyst-Abhranil/AlmaBetter-Capstone-Projects/blob/main/Copy_of_Assignment_NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [ ]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [ ]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
random_integers[:5,2:4].mean()





286058.5

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points
np.random.seed(20)
arr=np.random.randint(5,20,(10,2))
print(arr)


[[ 8 15]
 [17 15]
 [14  9]
 [16 11]
 [12  7]
 [ 5 11]
 [13 10]
 [15 15]
 [16  8]
 [ 5 18]]


In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
l=[]
for i in arr:
  print(i[:])







#euclidean_array=np.sqrt(arr1).reshape(10,10)
#euclidean_array










[ 8 15]
[17 15]
[14  9]
[16 11]
[12  7]
[ 5 11]
[13 10]
[15 15]
[16  8]
[ 5 18]


In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.


[ 0.  4.  5.  9.  8.  2.  3.  0.  4.  9.  4.  0.  9. 13. 12.  2.  1.  4.
  0. 13.  5.  9.  0.  4.  3.  7.  8.  5.  9.  4.  9. 13.  4.  0.  1. 11.
 12.  9. 13.  0.  8. 12.  3.  1.  0. 10. 11.  8. 12.  1.  2.  2.  7. 11.
 10.  0.  1.  2.  2. 11.  3.  1.  8. 12. 11.  1.  0.  3.  1. 12.  0.  4.
  5.  9.  8.  2.  3.  0.  4.  9.  4.  0.  9. 13. 12.  2.  1.  4.  0. 13.
  9. 13.  4.  0.  1. 11. 12.  9. 13.  0.]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here





# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..

np.random.seed(100)
random_matrix=np.random.randint(1,200,(10,10))
random_matrix











array([[  9,  25,  68, 104,  88,  80, 177, 139,  95, 181],
       [ 99,  54,  67,  15,  35,  25, 144, 108,  61,  59],
       [145, 138,  94,  87, 131, 156, 109, 133, 160, 130],
       [142, 101,   5,  92, 188,  68, 136,  50, 176, 194],
       [ 62,  15, 184,  81,   3, 122, 106, 148,  64, 182],
       [ 28,  57, 114, 159, 177,  48, 168, 110,  39, 173],
       [ 19, 193, 185, 163, 182,  18,  73,  14, 107,  31],
       [ 18,  54,  69, 179,  92, 182,  79,   1,  14, 186],
       [107, 132,  71, 132, 139, 189, 132, 106, 177, 181],
       [ 44,  37,   6,  72,  39,  95, 171,  85,  96, 115]])

In [ ]:
list1=[]
for i in range(8):
  for j in range(8):
    list1.append(random_matrix[i:i+3,j:j+3])
array1=np.array(list1)
print(array1)

[[[  9  25  68]
  [ 99  54  67]
  [145 138  94]]

 [[ 25  68 104]
  [ 54  67  15]
  [138  94  87]]

 [[ 68 104  88]
  [ 67  15  35]
  [ 94  87 131]]

 [[104  88  80]
  [ 15  35  25]
  [ 87 131 156]]

 [[ 88  80 177]
  [ 35  25 144]
  [131 156 109]]

 [[ 80 177 139]
  [ 25 144 108]
  [156 109 133]]

 [[177 139  95]
  [144 108  61]
  [109 133 160]]

 [[139  95 181]
  [108  61  59]
  [133 160 130]]

 [[ 99  54  67]
  [145 138  94]
  [142 101   5]]

 [[ 54  67  15]
  [138  94  87]
  [101   5  92]]

 [[ 67  15  35]
  [ 94  87 131]
  [  5  92 188]]

 [[ 15  35  25]
  [ 87 131 156]
  [ 92 188  68]]

 [[ 35  25 144]
  [131 156 109]
  [188  68 136]]

 [[ 25 144 108]
  [156 109 133]
  [ 68 136  50]]

 [[144 108  61]
  [109 133 160]
  [136  50 176]]

 [[108  61  59]
  [133 160 130]
  [ 50 176 194]]

 [[145 138  94]
  [142 101   5]
  [ 62  15 184]]

 [[138  94  87]
  [101   5  92]
  [ 15 184  81]]

 [[ 94  87 131]
  [  5  92 188]
  [184  81   3]]

 [[ 87 131 156]
  [ 92 188  68]
  [ 81   3 122]]



#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
# Your function below
def nearest_value_finder(arr,n):
  x=np.sort(arr)
  for i in range(len(x)):
    if x[i]==n and x[i+1]-n>x[i-1]-n:
      return x[i-1]
    elif x[i]==n and x[i+1]-n<x[i-1]-n:
      return x[i+1]






In [ ]:
np.random.seed(15)
arr1=np.random.randint(10,500,15)
arr1

array([466, 255, 406, 143, 385, 394, 166, 165, 209, 213,  95, 128, 441,
       231,  27])

In [ ]:
nearest_value_finder(arr1,143)

128

In [ ]:
nearest_value_finder(arr1,394)

385